name: Auto Labeling
on: [pull_request]

jobs:
  assign:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: write
      repository-projects: read
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
      NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: Add feature label
        if: ${{ startsWith(github.head_ref, 'feat/') }}
        run: gh pr edit $NUMBER --add-label feature

      - name: Add bug label
        if: ${{ startsWith(github.head_ref, 'fix/') }}
        run: gh pr edit $NUMBER --add-label bug

      - name: Add emergency label
        if: ${{ startsWith(github.head_ref, 'hotfix/') }}
        run: gh pr edit $NUMBER --add-label emergency

      - name: Add refactor label
        if: ${{ startsWith(github.head_ref, 'refactor/') }}
        run: gh pr edit $NUMBER --add-label refactor

      - name: Add chore label
        if: ${{ startsWith(github.head_ref, 'chore/') }}
        run: gh pr edit $NUMBER --add-label chore

      - name: Add documentation label
        if: ${{ startsWith(github.head_ref, 'docs/') }}
        run: gh pr edit $NUMBER --add-label documentation

      - name: Add revert label
        if: ${{ startsWith(github.head_ref, 'revert/') }}
        run: gh pr edit $NUMBER --add-label revert
